name: Hourly Fetch Data

on:
  schedule:
    - cron: '0 * * * *'   # runs at minute 0 every hour
  workflow_dispatch:       # manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run fetch_data.py
      run: python fetch_data.py

    - name: Configure Git
      run: |
        git config --global user.name "maheenrizwan11"
        git config --global user.email "maheenrizwan10@gmail.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit changes
      run: |
        git add data/raw/*.json
        git commit -m "Auto-update raw data (hourly)"
        git push
